### PR TITLE
Old style exception --> new style for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Old style exceptions are syntax errors in Python3 but new style exceptions work as expected in both Python 2 and Python 3.

[flake8](http://flake8.pycqa.org) testing of https://github.com/testerSunshine/12306 on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./agency/agency_tools.py:58:29: E999 SyntaxError: invalid syntax
            except Exception, e:
                            ^
1     E999 SyntaxError: invalid syntax
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by jonwinters** [comment]
@cclauss  are you a robot?

**Comment by cclauss** [comment]
Nope.  Just a human who uses tools.

In this case, I used continuous integration (Travis CI) and a linter (flake8) to find syntax errors and undefined names...

[flake8](http://flake8.pycqa.org) testing of https://github.com/testerSunshine/12306 on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./inter/GetRandCode.py:50:17: F821 undefined name 'raw_input'
        Ofset = raw_input(u"输入对应的验证码: ")
                ^
./inter/GetPassengerDTOs.py:88:22: F821 undefined name 'xrange'
            for i in xrange(self.is_more_ticket_num):
                     ^
./agency/agency_tools.py:58:29: E999 SyntaxError: invalid syntax
            except Exception, e:
                            ^
./agency/cdn_utils.py:11:5: F821 undefined name 'reload'
    reload(sys)
    ^
./init/select_ticket_info.py:34:5: F821 undefined name 'reload'
    reload(sys)
    ^
1     E999 SyntaxError: invalid syntax
4     F821 undefined name 'reload'
5
```

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by jonwinters** [comment]
@cclauss  I am so curious about people who are not from China open a pull request for thie repo , so  your guys need high train ticket  in our spring Festival ？

**Comment by cclauss** [comment]
@jonwinters For this year's Spring Festival, _Python 2 is good enough_ but http://pythonclock.org is very clear that __Python 2 will not be safe for next year's Spring Festival__.  Along with #20 the goal is to ensure that this software contains few Python 3 incompatibilities so that it will be ready for next year and many Spring Festival's to come.  https://twitter.com/raymondh/status/1080961135493316608

**Pull request closed without merging**
